

version: "2"

linters:
  default: none
  enable:
      - asciicheck
      - bidichk
      - copyloopvar
      - embeddedstructfieldcheck
      - err113
      - errchkjson
      - errname
      - errorlint
      - exhaustive
      - fatcontext
      - gocheckcompilerdirectives
      - gocognit
      - gocritic
      - godoclint
      - godot
      - gosec
      - govet
      - iface
      - inamedparam
      - ineffassign
      - intrange

      # Reports long lines.
      - lll

      # A suite of analyzers that suggest simplifications to Go code, using modern language and library features.
      - modernize 

      # Find the code that returns nil even if it checks that the error is not nil.
      - nilerr 

      # Checks for a new line before return and branch statements to increase code clarity.
      - nlreturn

      # Checks that fmt.Sprintf can be replaced with a faster alternative.
      - perfsprint

      # Find slice declarations that could potentially be pre-allocated.
      - prealloc

      # Find code that shadows one of Go's predeclared identifiers.
      - predeclared

      # Checks that package variables are not reassigned.
      - reassign

      # Checks whether Rows.Err of rows is checked successfully.
      - rowserrcheck

      # Checks that sql.Rows, sql.Stmt, sqlx.NamedStmt, pgx.Query are closed.
      - sqlclosecheck

      # It's the set of rules from staticcheck.
      - staticcheck

      # Check that struct tags are well aligned.
      - tagalign

      # Checks Go code for unused constants, variables, functions and types.
      - unused

      # A linter that detect the possibility to use variables/constants from the Go standard library.
      - usestdlibvars

      # Reports uses of functions with replacement inside the testing package.
      - usetesting

      # Finds wasted assignment statements.
      - wastedassign

      # Detects the wrong usage of zerolog that a user forgets to dispatch with Send or Msg.
      - zerologlint

  settings:
      nlreturn:
        # Size of the block (including return statement that is still "OK"),
        # so no return split required.
        block-size: 2
      copyloopvar:
          # Check all assigning the loop variable to another variable.
          check-alias: true
      embeddedstructfieldcheck:
          # Checks that there is an empty space between the embedded fields and regular fields.
          empty-line: false
          # Checks that sync.Mutex and sync.RWMutex are not used as embedded fields.
          forbid-mutex: true
      rowserrcheck:
        # database/sql is always checked.
        packages:
          - github.com/jmoiron/sqlx
          - github.com/vinovest/sqlx

      gocritic:
        disabled-checks:
          - "sloppyLen"

      staticcheck:
        # Default: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]
        checks:
          - "all"
          - "-QF1011"
          - "-ST1000"
          - "-ST1003"
          - "-ST1023"


            
formatters:
  # Enable specific formatter.
  # Default: [] (uses standard Go formatting)
  enable:
    - gofmt
    - goimports
    - golines
    - swaggo

  # Formatters settings.
  settings:
    gofmt:
      # Apply the rewrite rules to the source before reformatting.
      # https://pkg.go.dev/cmd/gofmt
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
        - pattern: 'a[b:len(a)]'
          replacement: 'a[b:]'

    golines:
      max-len: 120
      tab-len: 4
      shorten-comments: true
      reformat-tags: true
      chain-split-dots: true


run:
  # Timeout for total work, e.g. 30s, 5m, 5m30s.
  # If the value is lower or equal to 0, the timeout is disabled.
  # Default: 0 (disabled)
  timeout: 1m


severity:
  default: error

