project_name: karopon
release:
  disable: true
builds:
  - id: linux-amd64
    main: ./
    goos: [linux]
    goarch: ['amd64']
    env: [CGO_ENABLED=0]
    flags: ['-tags="netgo osusergo"']
    ldflags: ["-s","-w","-X main.BuildDate={{.Date}}","-X main.BuildMode=prod","-X main.BuildCommit={{.Commit}}","-X main.BuildVersion={{.Version}}"]
  - id: linux-386
    main: ./
    goos: [linux]
    goarch: ['386']
    env: [CGO_ENABLED=0]
    flags: ['-tags="netgo osusergo"']
    ldflags: ["-s","-w","-X main.BuildDate={{.Date}}","-X main.BuildMode=prod","-X main.BuildCommit={{.Commit}}","-X main.BuildVersion={{.Version}}"]
  - id: linux-armhf
    main: ./
    goos: [linux]
    goarch: [arm]
    goarm: [7]
    env: [CGO_ENABLED=0]
    flags: ['-tags="netgo osusergo"']
    ldflags: ["-s","-w","-X main.BuildDate={{.Date}}","-X main.BuildMode=prod","-X main.BuildCommit={{.Commit}}","-X main.BuildVersion={{.Version}}"]
  - id: linux-arm64
    main: ./
    goos: [linux]
    goarch: [arm64]
    env: [CGO_ENABLED=0]
    flags: ['-tags="netgo osusergo"']
    ldflags: ["-s","-w","-X main.BuildDate={{.Date}}","-X main.BuildMode=prod","-X main.BuildCommit={{.Commit}}","-X main.BuildVersion={{.Version}}"]
  - id: windows-amd64
    main: ./
    goos: [windows]
    goarch: [amd64]
    env: [CGO_ENABLED=0]
    flags: ['-tags="netgo osusergo"']
    ldflags: ["-s","-w","-X main.BuildDate={{.Date}}","-X main.BuildMode=prod","-X main.BuildCommit={{.Commit}}","-X main.BuildVersion={{.Version}}"]
archives:
  - files:
      - LICENSE
      - README.md
      - .env
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{- if eq .Arch "386" }}i386{{- else }}{{ .Arch }}{{ end }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
checksum:
  disable: true
changelog:
  disable: true
dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/minnowo/karopon:amd64-latest"
      - "ghcr.io/minnowo/karopon:amd64-{{ .RawVersion }}"
    dockerfile: docker/Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: '386'
    image_templates:
      - "ghcr.io/minnowo/karopon:386-latest"
      - "ghcr.io/minnowo/karopon:386-{{ .RawVersion }}"
    dockerfile: docker/Dockerfile
    build_flag_templates:
      - "--platform=linux/386"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/minnowo/karopon:arm64-latest"
      - "ghcr.io/minnowo/karopon:arm64-{{ .RawVersion }}"
    dockerfile: docker/Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm
    goarm: 7
    image_templates:
      - "ghcr.io/minnowo/karopon:armv7-latest"
      - "ghcr.io/minnowo/karopon:armv7-{{ .RawVersion }}"
    dockerfile: docker/Dockerfile
    build_flag_templates:
      - "--platform=linux/arm/v7"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
docker_manifests:
  - name_template: "ghcr.io/minnowo/karopon:latest"
    image_templates:
      - "ghcr.io/minnowo/karopon:amd64-latest"
      - "ghcr.io/minnowo/karopon:386-latest"
      - "ghcr.io/minnowo/karopon:arm64-latest"
      - "ghcr.io/minnowo/karopon:armv7-latest"
  - name_template: "ghcr.io/minnowo/karopon:{{ .RawVersion }}"
    image_templates:
      - "ghcr.io/minnowo/karopon:amd64-{{ .RawVersion }}"
      - "ghcr.io/minnowo/karopon:386-{{ .RawVersion }}"
      - "ghcr.io/minnowo/karopon:arm64-{{ .RawVersion }}"
      - "ghcr.io/minnowo/karopon:armv7-{{ .RawVersion }}"
