
-- sqlite doesn't have schemas

CREATE TABLE IF NOT EXISTS PON_CONFIG (
    VERSION INTEGER PRIMARY KEY NOT NULL
);
INSERT INTO PON_CONFIG (VERSION) VALUES (0);

CREATE TABLE IF NOT EXISTS PON_USER (
    ID       INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    NAME     TEXT UNIQUE,
    PASSWORD BLOB,
    CREATED  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    THEME                       TEXT NOT NULL DEFAULT 'auto',
    SHOW_DIABETES               INTEGER NOT NULL DEFAULT TRUE,
    CALORIC_CALC_METHOD         TEXT NOT NULL DEFAULT 'auto',
    INSULIN_SENSITIVITY_FACTOR  REAL NOT NULL DEFAULT 3,
    TARGET_BLOOD_SUGAR          REAL NOT NULL DEFAULT 5.6,
    EVENT_HISTORY_FETCH_LIMIT   INTEGER NOT NULL DEFAULT 50,
    SESSION_EXPIRE_TIME_SECONDS INTEGER NOT NULL DEFAULT (60 * 60 * 24),
    TIME_FORMAT                 TEXT NOT NULL DEFAULT '24-hour',
    DATE_FORMAT                 TEXT NOT NULL DEFAULT 'auto'
);

CREATE TABLE IF NOT EXISTS PON_USER_EVENT (
    ID         INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    USER_ID    INTEGER NOT NULL,
    NAME       TEXT,
    UNIQUE (USER_ID, NAME),
    FOREIGN KEY (USER_ID) REFERENCES PON_USER(ID)
);

CREATE TABLE IF NOT EXISTS PON_USER_EVENTLOG (
    ID                         INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    USER_ID                    INTEGER NOT NULL,
    EVENT_ID                   INTEGER NOT NULL,
    CREATED                    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    USER_TIME                  TIMESTAMP NOT NULL,
    EVENT                      TEXT NOT NULL,
    NET_CARBS                  REAL NOT NULL,
    BLOOD_GLUCOSE              REAL NOT NULL,
    INSULIN_SENSITIVITY_FACTOR REAL NOT NULL,
    INSULIN_TO_CARB_RATIO      REAL NOT NULL,
    BLOOD_GLUCOSE_TARGET       REAL NOT NULL,
    RECOMMENDED_INSULIN_AMOUNT REAL NOT NULL,
    ACTUAL_INSULIN_TAKEN       REAL NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES PON_USER(ID),
    FOREIGN KEY (EVENT_ID) REFERENCES PON_USER_EVENT(ID)
);

CREATE TABLE IF NOT EXISTS PON_USER_FOOD (
    ID      INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    NAME    TEXT NOT NULL,
    UNIT    TEXT,
    PORTION REAL NOT NULL,
    PROTEIN REAL NOT NULL,
    CARB    REAL NOT NULL,
    FIBRE   REAL NOT NULL,
    FAT     REAL NOT NULL,
    UNIQUE (USER_ID, NAME, UNIT),
    FOREIGN KEY (USER_ID) REFERENCES PON_USER(ID)
);


CREATE TABLE IF NOT EXISTS PON_USER_FOODLOG (
    ID      INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    FOOD_ID INTEGER,
    CREATED   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    USER_TIME TIMESTAMP NOT NULL,
    NAME    TEXT NOT NULL,
    EVENTLOG_ID INTEGER,
    EVENT_ID INTEGER,
    EVENT   TEXT NOT NULL,
    UNIT    TEXT NOT NULL,
    PORTION REAL NOT NULL,
    PROTEIN REAL NOT NULL,
    CARB    REAL NOT NULL,
    FIBRE   REAL NOT NULL,
    FAT     REAL NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES PON_USER(ID),
    FOREIGN KEY (FOOD_ID) REFERENCES PON_USER_FOOD(ID) ON DELETE SET NULL,
    FOREIGN KEY (EVENTLOG_ID) REFERENCES PON_USER_EVENTLOG(ID),
    FOREIGN KEY (EVENT_ID) REFERENCES PON_USER_EVENT(ID)
);


CREATE TABLE IF NOT EXISTS PON_USER_BODYLOG (
    ID                         INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID                    INTEGER NOT NULL,
    CREATED                    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    USER_TIME                  TIMESTAMP NOT NULL,

    -- Core metrics
    WEIGHT_KG                  REAL,
    HEIGHT_CM                  REAL,
    BODY_FAT_PERCENT           REAL,
    BMI                        REAL,

    -- Blood pressure & heart
    BP_SYSTOLIC                REAL,
    BP_DIASTOLIC               REAL,
    HEART_RATE_BPM             REAL,

    -- Lifestyle data
    STEPS_COUNT                INTEGER,

    FOREIGN KEY (USER_ID) REFERENCES PON_USER(ID)
);

CREATE TABLE IF NOT EXISTS PON_DATA_SOURCE (
    ID                  INTEGER PRIMARY KEY AUTOINCREMENT,
    CREATED             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NAME                TEXT UNIQUE NOT NULL,
    URL                 TEXT,
    NOTES               TEXT
);

CREATE TABLE IF NOT EXISTS PON_DATA_SOURCE_FOOD (
    ID                  INTEGER PRIMARY KEY AUTOINCREMENT,
    DATA_SOURCE_ID      INTEGER NOT NULL,
    CREATED             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NAME                TEXT NOT NULL,
    UNIT                TEXT,
    PORTION             REAL NOT NULL,
    PROTEIN             REAL NOT NULL,
    CARB                REAL NOT NULL,
    FIBRE               REAL NOT NULL,
    FAT                 REAL NOT NULL,
    DATA_SOURCE_ROW_INT_ID INTEGER,  -- FDC ID, ndbNumber, etc.
    FOREIGN KEY (DATA_SOURCE_ID) REFERENCES PON_DATA_SOURCE(ID) ON DELETE CASCADE
);

-- Index for DATA_SOURCE_FOOD (by name, case-insensitive)
CREATE INDEX IF NOT EXISTS idx_datasourcefood_foodname
ON PON_DATA_SOURCE_FOOD (DATA_SOURCE_ID, LOWER(NAME));

-- Index for DATA_SOURCE_FOOD (by the data source row integer ID)
CREATE INDEX IF NOT EXISTS idx_datasourcefood_datasourcerowintid
ON PON_DATA_SOURCE_FOOD (DATA_SOURCE_ROW_INT_ID);

/*
-- Sqlite doesn't have trigram matching like Postgres.
-- Instead we're using Full text search
-- https://sqlite.org/fts5.html
CREATE VIRTUAL TABLE IF NOT EXISTS PON_DATA_SOURCE_FOOD_FTS
USING fts5(
    NAME,  -- the column to be indexed for fuzzy search
    content=pon_data_source_food,  -- reference the main table
    content_rowid=rowid,  -- the row ID from the main table (this will link to the main table)
    tokenize=unicode61
);
*/


CREATE TABLE IF NOT EXISTS PON_USER_GOAL (
    ID                  INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID             INTEGER NOT NULL,
    CREATED             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    NAME                TEXT UNIQUE NOT NULL,

    -- String values for this will be hard coded in Golang
    TARGET_VALUE        REAL NOT NULL, -- the value they're aiming for
    TARGET_COL          TEXT NOT NULL, -- the column they want to target a value in, carbs, net carbs, etc
    AGGREGATION_TYPE    TEXT NOT NULL, -- SUM, AVG, MIN, MAX, etc, generates the current value
    VALUE_COMPARISON    TEXT NOT NULL, -- EQ, LESS_THAN, MORE_THAN, etc, how to cmpare the current value with the target value

    -- As of creating this, it's just a simple interval, [daily, weekly, etc]
    -- This might change in the future depending on what happens.
    TIME_EXPR           TEXT NOT NULL,

    -- Add a foreign key constraint for USER_ID
    FOREIGN KEY (USER_ID) REFERENCES PON_USER(ID)
);



CREATE TABLE IF NOT EXISTS PON_USER_TAG (
    ID                  INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID             INTEGER NOT NULL,
    CREATED             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NAMESPACE           TEXT NOT NULL,
    NAME                TEXT NOT NULL,
    UNIQUE (USER_ID, NAMESPACE, NAME),
    FOREIGN KEY (USER_ID) REFERENCES PON_USER(ID)
);

CREATE INDEX IF NOT EXISTS idx_usertag_usernamespacename
ON PON_USER_TAG (USER_ID, NAMESPACE, NAME);

CREATE TABLE IF NOT EXISTS PON_USER_TIMESPAN (
    ID                  INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID             INTEGER NOT NULL,
    CREATED             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    START_TIME          TIMESTAMP NOT NULL,
    STOP_TIME           TIMESTAMP NOT NULL,
    NOTE                TEXT,
    FOREIGN KEY (USER_ID) REFERENCES PON_USER(ID)
);

CREATE TABLE IF NOT EXISTS PON_USER_TIMESPAN_TAG (
    TIMESPAN_ID         INTEGER NOT NULL,
    TAG_ID              INTEGER NOT NULL,
    FOREIGN KEY (TIMESPAN_ID) REFERENCES PON_USER_TIMESPAN(ID) ON DELETE CASCADE,
    FOREIGN KEY (TAG_ID) REFERENCES PON_USER_TAG(ID)
);


CREATE TABLE IF NOT EXISTS PON_USER_SESSION (
    USER_ID   INTEGER NOT NULL,
    CREATED   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EXPIRES   TIMESTAMP NOT NULL,
    TOKEN     BLOB NOT NULL CHECK (LENGTH(TOKEN) = 32),
    PRIMARY KEY (USER_ID, TOKEN),
    FOREIGN KEY (USER_ID) REFERENCES PON_USER(ID)
);

CREATE INDEX IF NOT EXISTS idx_usersession_token
ON PON_USER_SESSION (TOKEN);



