CREATE TABLE IF NOT EXISTS PON_USER_DASHBOARD (
    ID      INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    USER_ID INTEGER NOT NULL,
    NAME    TEXT    NOT NULL DEFAULT 'Default',
    DATA    TEXT    NOT NULL DEFAULT '[]',
    FOREIGN KEY (USER_ID) REFERENCES PON_USER(ID)
);
