CREATE TABLE IF NOT EXISTS PON_USER_TAG_COLOR (
    USER_ID   INTEGER NOT NULL,
    NAMESPACE TEXT    NOT NULL,
    COLOR     TEXT    NOT NULL,
    PRIMARY KEY (USER_ID, NAMESPACE),
    FOREIGN KEY (USER_ID) REFERENCES PON_USER(ID)
);
