CREATE TABLE IF NOT EXISTS PON_USER_PHOTO (
    ID      INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    USER_ID INTEGER NOT NULL,
    DATA    BLOB    NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES PON_USER(ID)
);

CREATE TABLE IF NOT EXISTS PON_USER_EVENTLOG_PHOTO (
    EVENTLOG_ID INTEGER NOT NULL,
    PHOTO_ID    INTEGER NOT NULL,
    PRIMARY KEY (EVENTLOG_ID, PHOTO_ID),
    FOREIGN KEY (EVENTLOG_ID) REFERENCES PON_USER_EVENTLOG(ID) ON DELETE CASCADE,
    FOREIGN KEY (PHOTO_ID)    REFERENCES PON_USER_PHOTO(ID)    ON DELETE CASCADE
);
