

CREATE TABLE IF NOT EXISTS PON_USER_ACTIVITY (
    ID                  INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID             INTEGER NOT NULL,
    CREATED             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    NAME                TEXT NOT NULL,
    TAG_ID              INTEGER NOT NULL,
    DURATION            INTEGER NOT NULL,
    NOTE                TEXT NOT NULL DEFAULT '',

    FOREIGN KEY (USER_ID) REFERENCES PON_USER(ID),
    FOREIGN KEY (TAG_ID) REFERENCES PON_USER_TAG(ID)
);

CREATE TABLE IF NOT EXISTS PON_USER_REMINDER (
    ID                  INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID             INTEGER NOT NULL,
    CREATED             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    ENABLED             INTEGER NOT NULL DEFAULT 1,
    INTERVAL_MINUTES    INTEGER NOT NULL,
    LAST_ACTIVITY_AT    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (USER_ID) REFERENCES PON_USER(ID)
);

CREATE TABLE IF NOT EXISTS PON_USER_REMINDER_ACTIVITY (
    REMINDER_ID         INTEGER NOT NULL,
    ACTIVITY_ID         INTEGER NOT NULL,

    FOREIGN KEY (REMINDER_ID) REFERENCES PON_USER_REMINDER(ID) ON DELETE CASCADE,
    FOREIGN KEY (ACTIVITY_ID) REFERENCES PON_USER_ACTIVITY(ID) ON DELETE CASCADE
);
