ALTER TABLE PON_USER_REMINDER
ADD COLUMN ACTIVITY_MODE TEXT NOT NULL DEFAULT 'random';

ALTER TABLE PON_USER_REMINDER
ADD COLUMN ACTIVE_TIMERS TEXT NOT NULL DEFAULT '{}';

ALTER TABLE PON_USER_REMINDER
ADD COLUMN SOUND TEXT NOT NULL DEFAULT 'chime';

ALTER TABLE PON_USER_REMINDER
ADD COLUMN NAME TEXT NOT NULL DEFAULT '';
