
CREATE TABLE IF NOT EXISTS PON_USER_EXERCISE (
    ID                  INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID             INTEGER NOT NULL,
    CREATED             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    NAME                TEXT NOT NULL,
    NOTE                TEXT NOT NULL DEFAULT '',

    FOREIGN KEY (USER_ID) REFERENCES PON_USER(ID)
);

CREATE TABLE IF NOT EXISTS PON_USER_EXERCISE_TAG (
    EXERCISE_ID         INTEGER NOT NULL,
    TAG_ID              INTEGER NOT NULL,

    FOREIGN KEY (EXERCISE_ID) REFERENCES PON_USER_EXERCISE(ID) ON DELETE CASCADE,
    FOREIGN KEY (TAG_ID) REFERENCES PON_USER_TAG(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PON_USER_WORKOUT (
    ID                  INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID             INTEGER NOT NULL,
    CREATED             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    NAME                TEXT NOT NULL,
    NOTE                TEXT NOT NULL DEFAULT '',

    -- JSON blob holding the workout's sets and steps.
    STRUCTURE           TEXT NOT NULL DEFAULT '',

    FOREIGN KEY (USER_ID) REFERENCES PON_USER(ID)
);

CREATE TABLE IF NOT EXISTS PON_USER_WORKOUT_TAG (
    WORKOUT_ID          INTEGER NOT NULL,
    TAG_ID              INTEGER NOT NULL,

    FOREIGN KEY (WORKOUT_ID) REFERENCES PON_USER_WORKOUT(ID) ON DELETE CASCADE,
    FOREIGN KEY (TAG_ID) REFERENCES PON_USER_TAG(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PON_USER_WORKOUTLOG (
    ID                  INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID             INTEGER NOT NULL,
    WORKOUT_ID          INTEGER,
    CREATED             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    NAME                TEXT NOT NULL,
    START_TIME          TIMESTAMP NOT NULL,
    STOP_TIME           TIMESTAMP NOT NULL,
    PAUSED_MS           INTEGER NOT NULL DEFAULT 0,
    COMPLETED           INTEGER NOT NULL DEFAULT 0,
    NOTE                TEXT NOT NULL DEFAULT '',

    FOREIGN KEY (USER_ID) REFERENCES PON_USER(ID),
    FOREIGN KEY (WORKOUT_ID) REFERENCES PON_USER_WORKOUT(ID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS PON_USER_WORKOUTLOG_STEP (
    ID                  INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID             INTEGER NOT NULL,
    WORKOUTLOG_ID       INTEGER NOT NULL,
    EXERCISE_ID         INTEGER,

    NAME                TEXT NOT NULL,
    KIND                TEXT NOT NULL,
    -- Where the step was in the workout when it ran, all counting from 1.
    -- e.g. SET_NUMBER = 2, ROUND = 3, STEP = 1 is the first step of the third round of the second set.
    SET_NUMBER          INTEGER NOT NULL,
    ROUND               INTEGER NOT NULL,
    STEP                INTEGER NOT NULL,

    TARGET_SECONDS      INTEGER NOT NULL DEFAULT 0,
    TARGET_REPS         INTEGER NOT NULL DEFAULT 0,
    TARGET_WEIGHT       REAL NOT NULL DEFAULT 0,
    TARGET_DISTANCE     REAL NOT NULL DEFAULT 0,
    ACTUAL_REPS         INTEGER NOT NULL DEFAULT 0,
    -- Seconds spent on the step, not counting pauses. 0 means it was skipped.
    ACTUAL_SECONDS      INTEGER NOT NULL DEFAULT 0,
    ACTUAL_WEIGHT       REAL NOT NULL DEFAULT 0,
    ACTUAL_DISTANCE     REAL NOT NULL DEFAULT 0,
    UNIT                TEXT NOT NULL DEFAULT '',

    FOREIGN KEY (USER_ID) REFERENCES PON_USER(ID),
    FOREIGN KEY (WORKOUTLOG_ID) REFERENCES PON_USER_WORKOUTLOG(ID) ON DELETE CASCADE,
    FOREIGN KEY (EXERCISE_ID) REFERENCES PON_USER_EXERCISE(ID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS PON_USER_WORKOUTLOG_TIMESPAN (
    WORKOUTLOG_ID       INTEGER NOT NULL,
    TIMESPAN_ID         INTEGER NOT NULL,

    FOREIGN KEY (WORKOUTLOG_ID) REFERENCES PON_USER_WORKOUTLOG(ID) ON DELETE CASCADE,
    FOREIGN KEY (TIMESPAN_ID) REFERENCES PON_USER_TIMESPAN(ID) ON DELETE CASCADE
);
