-- SQLite doesn't support altering the table, so we're going to just make a new table.
CREATE TABLE PON_USER_TIMESPAN_TAG_TMP (
    TIMESPAN_ID         INTEGER NOT NULL,
    TAG_ID              INTEGER NOT NULL,
    FOREIGN KEY (TIMESPAN_ID) REFERENCES PON_USER_TIMESPAN(ID) ON DELETE CASCADE,
    FOREIGN KEY (TAG_ID) REFERENCES PON_USER_TAG(ID) ON DELETE CASCADE
);

INSERT INTO PON_USER_TIMESPAN_TAG_TMP (TIMESPAN_ID, TAG_ID)
SELECT TIMESPAN_ID, TAG_ID FROM PON_USER_TIMESPAN_TAG;

DROP TABLE PON_USER_TIMESPAN_TAG;

ALTER TABLE PON_USER_TIMESPAN_TAG_TMP
RENAME TO PON_USER_TIMESPAN_TAG;
