
CREATE SCHEMA IF NOT EXISTS PON;

CREATE TABLE IF NOT EXISTS PON.CONFIG (
    VERSION INTEGER PRIMARY KEY NOT NULL
);

INSERT INTO PON.CONFIG (VERSION) VALUES (0);

CREATE TABLE IF NOT EXISTS PON.USER (
    ID       SERIAL PRIMARY KEY NOT NULL,
    NAME     VARCHAR(64) UNIQUE,
    PASSWORD BYTEA,
    CREATED  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- event is considered to be 'breakfast', 'lunch', 'dinner', etc
CREATE TABLE IF NOT EXISTS PON.USER_EVENT (
    ID         SERIAL PRIMARY KEY NOT NULL,
    USER_ID    INTEGER NOT NULL REFERENCES PON.USER(ID),
    NAME       VARCHAR(64),
    UNIQUE (USER_ID, NAME)
);

CREATE TABLE IF NOT EXISTS PON.USER_EVENTLOG (
    ID                         SERIAL PRIMARY KEY NOT NULL,
    USER_ID                    INTEGER NOT NULL REFERENCES PON.USER(ID),
    EVENT_ID                   INTEGER NOT NULL REFERENCES PON.USER_EVENT(ID),
    CREATED                    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    USER_TIME                  TIMESTAMP NOT NULL,
    EVENT                      VARCHAR(64) NOT NULL,
    NET_CARBS                  FLOAT NOT NULL,
    BLOOD_GLUCOSE              FLOAT NOT NULL,
    INSULIN_SENSITIVITY_FACTOR FLOAT NOT NULL,
    INSULIN_TO_CARB_RATIO      FLOAT NOT NULL,
    BLOOD_GLUCOSE_TARGET       FLOAT NOT NULL,
    RECOMMENDED_INSULIN_AMOUNT FLOAT NOT NULL,
    ACTUAL_INSULIN_TAKEN       FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS PON.USER_FOOD (
    ID      SERIAL PRIMARY KEY,
    USER_ID INTEGER NOT NULL REFERENCES PON.USER(ID),
    NAME    VARCHAR(255) NOT NULL,
    UNIT    VARCHAR(64),
    PORTION FLOAT  NOT NULL,
    PROTEIN FLOAT  NOT NULL,
    CARB    FLOAT  NOT NULL,
    FIBRE   FLOAT  NOT NULL,
    FAT     FLOAT  NOT NULL,
    UNIQUE (USER_ID, NAME, UNIT)
);

CREATE TABLE IF NOT EXISTS PON.USER_FOODLOG (
    ID      SERIAL,
    USER_ID INTEGER NOT NULL REFERENCES PON.USER(ID),
    FOOD_ID INTEGER NOT NULL REFERENCES PON.USER_FOOD(ID),

    CREATED   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    USER_TIME TIMESTAMP NOT NULL,

    NAME    VARCHAR(255) NOT NULL,

    EVENTLOG_ID INTEGER REFERENCES PON.USER_EVENTLOG(ID),
    EVENT_ID INTEGER REFERENCES PON.USER_EVENT(ID),
    EVENT   VARCHAR(64) NOT NULL,

    UNIT    VARCHAR(64) NOT NULL,
    PORTION FLOAT NOT NULL,
    PROTEIN FLOAT NOT NULL,
    CARB    FLOAT NOT NULL,
    FIBRE   FLOAT NOT NULL,
    FAT     FLOAT NOT NULL,
    PRIMARY KEY (ID, USER_ID)


    
);