CREATE TABLE IF NOT EXISTS PON.USER_SETTINGS (
    ID                          SERIAL PRIMARY KEY,
    USER_ID                     INTEGER UNIQUE REFERENCES PON.USER(ID),
    DARK_MODE                   BOOLEAN NOT NULL,
    SHOW_DIABETES               BOOLEAN NOT NULL,
    CALORIC_CALC_METHOD         VARCHAR(64) NOT NULL,
    INSULIN_SENSITIVITY_FACTOR  FLOAT NOT NULL
);