CREATE TABLE IF NOT EXISTS PON.USER_SETTINGS (
    USER_ID                     INTEGER PRIMARY KEY REFERENCES PON.USER(ID),
    DARK_MODE                   BOOLEAN NOT NULL,
    SHOW_DIABETES               BOOLEAN NOT NULL,
    CALORIC_CALC_METHOD         VARCHAR(64) NOT NULL,
    INSULIN_SENSITIVITY_FACTOR  FLOAT NOT NULL
);

INSERT INTO PON.USER_SETTINGS (
    USER_ID, DARK_MODE, SHOW_DIABETES, CALORIC_CALC_METHOD, INSULIN_SENSITIVITY_FACTOR
)
SELECT id, true, true, 'auto', 0.01
FROM PON.USER u
WHERE NOT EXISTS (
    SELECT 1 FROM PON.USER_SETTINGS s WHERE s.USER_ID = u.id
)
