
-- Just merge the settings table into the user table for ease of everything.

ALTER TABLE PON.USER
ADD COLUMN DARK_MODE BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE PON.USER
ADD COLUMN SHOW_DIABETES BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE PON.USER
ADD COLUMN CALORIC_CALC_METHOD VARCHAR(64) NOT NULL DEFAULT 'auto';

ALTER TABLE PON.USER
ADD COLUMN INSULIN_SENSITIVITY_FACTOR FLOAT NOT NULL DEFAULT 3;

--
-- new settings
--

ALTER TABLE PON.USER
ADD COLUMN TARGET_BLOOD_SUGAR FLOAT NOT NULL DEFAULT 5.6;

-- This will limit the event history to fetching this many items
ALTER TABLE PON.USER 
ADD COLUMN EVENT_HISTORY_FETCH_LIMIT INTEGER NOT NULL DEFAULT 50;


-- We don't care about preserving settings at this point in time
DROP TABLE PON.USER_SETTINGS;



