
ALTER TABLE PON.USER
ADD COLUMN SESSION_EXPIRE_TIME_SECONDS BIGINT NOT NULL DEFAULT (60 * 60 * 24);

ALTER TABLE PON.USER
ADD COLUMN TIME_FORMAT VARCHAR(64) NOT NULL DEFAULT '24-hour';

ALTER TABLE PON.USER
ADD COLUMN DATE_FORMAT VARCHAR(64) NOT NULL DEFAULT 'auto';

