

UPDATE PON.USER_GOAL
SET VALUE_COMPARISON = 'GREATER_THAN'
WHERE VALUE_COMPARISON = 'MORE_THAN';

UPDATE PON.USER_GOAL
SET VALUE_COMPARISON = 'GREATER_THAN_OR_EQUAL_TO'
WHERE VALUE_COMPARISON = 'MORE_THAN_OR_EQUAL_TO';




