

CREATE TABLE IF NOT EXISTS PON.USER_TAG (
    ID                  SERIAL PRIMARY KEY,
    USER_ID             INTEGER NOT NULL REFERENCES PON.USER(ID),
    CREATED             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    NAMESPACE VARCHAR(128) NOT NULL,
    NAME VARCHAR(128) NOT NULL,

    UNIQUE (NAMESPACE, NAME)
);

CREATE INDEX IF NOT EXISTS idx_usertag_usernamespacename
ON PON.USER_TAG (USER_ID, NAMESPACE, NAME);

CREATE TABLE IF NOT EXISTS PON.USER_TIMESPAN (
    ID                  SERIAL PRIMARY KEY,
    USER_ID             INTEGER NOT NULL REFERENCES PON.USER(ID),
    CREATED             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    START_TIME TIMESTAMP NOT NULL,
    STOP_TIME TIMESTAMP NOT NULL,

    NOTE TEXT
);

CREATE TABLE IF NOT EXISTS PON.USER_TIMESPAN_TAG (
    TIMESPAN_ID   INTEGER NOT NULL REFERENCES PON.USER_TIMESPAN(ID),
    TAG_ID        INTEGER NOT NULL REFERENCES PON.USER_TAG(ID)
);

