

CREATE TABLE IF NOT EXISTS PON.USER_SESSION (
    USER_ID   INTEGER NOT NULL REFERENCES PON.USER(ID),
    CREATED   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EXPIRES   TIMESTAMP NOT NULL,
    TOKEN     BYTEA NOT NULL CHECK (octet_length(TOKEN) = 32),
    PRIMARY KEY (USER_ID, TOKEN)
);

CREATE INDEX IF NOT EXISTS idx_usersession_token
ON PON.USER_SESSION (TOKEN);

