CREATE TABLE IF NOT EXISTS PON.USER_PHOTO (
    id      SERIAL  PRIMARY KEY NOT NULL,
    user_id INTEGER NOT NULL REFERENCES PON.USER(id),
    data    BYTEA   NOT NULL
);

CREATE TABLE IF NOT EXISTS PON.USER_EVENTLOG_PHOTO (
    eventlog_id INTEGER NOT NULL REFERENCES PON.USER_EVENTLOG(id) ON DELETE CASCADE,
    photo_id    INTEGER NOT NULL REFERENCES PON.USER_PHOTO(id)    ON DELETE CASCADE,
    PRIMARY KEY (eventlog_id, photo_id)
);
