
-- This migration is to refactor the bodylog to be more flexible as per user request.
-- User's want to define their own body metrics, such as waist size.
--
-- This requires dynamic shape, so we'll need to split this table into multiple.

ALTER TABLE PON.USER_BODYLOG RENAME TO USER_BODYLOG_OLD;

-- This is a user-defined body metric they care about.
-- This table only defines the shape, doesn't hold any values.
-- Weight KG, Height CM, etc
CREATE TABLE IF NOT EXISTS PON.USER_BODY_METRIC (
    ID         SERIAL PRIMARY KEY NOT NULL,
    USER_ID    INTEGER NOT NULL REFERENCES PON.USER(ID),
    NAME       VARCHAR(64),
    UNIT       VARCHAR(64),
    UNIQUE (USER_ID, NAME)
);

-- The new bodylog table.
-- Only needs to hold the ID and time for linking to subtables,
-- since we don't know the BODY_METRICs ahead of time.
CREATE TABLE IF NOT EXISTS PON.USER_BODYLOG (
    ID                         SERIAL PRIMARY KEY NOT NULL,
    USER_ID                    INTEGER NOT NULL REFERENCES PON.USER(ID),
    CREATED                    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    USER_TIME                  TIMESTAMP NOT NULL
);

-- The link table which handles value association of the BODYLOG with the BODY_METRICs.
CREATE TABLE IF NOT EXISTS PON.USER_BODYLOG_METRIC (
    BODYLOG_ID         INTEGER NOT NULL REFERENCES PON.USER_BODYLOG(ID) ON DELETE CASCADE,
    BODY_METRIC_ID     INTEGER NOT NULL REFERENCES PON.USER_BODY_METRIC(ID),
    VALUE              FLOAT NOT NULL
);

-- seed a body metric definition per user for each legacy column they have data for
INSERT INTO PON.USER_BODY_METRIC (USER_ID, NAME, UNIT)
    SELECT DISTINCT USER_ID, 'Weight', 'kg' FROM PON.USER_BODYLOG_OLD WHERE WEIGHT_KG IS NOT NULL
    UNION ALL
    SELECT DISTINCT USER_ID, 'Height', 'cm' FROM PON.USER_BODYLOG_OLD WHERE HEIGHT_CM IS NOT NULL
    UNION ALL
    SELECT DISTINCT USER_ID, 'Body Fat', '%' FROM PON.USER_BODYLOG_OLD WHERE BODY_FAT_PERCENT IS NOT NULL
    UNION ALL
    SELECT DISTINCT USER_ID, 'BMI', 'bmi' FROM PON.USER_BODYLOG_OLD WHERE BMI IS NOT NULL
    UNION ALL
    SELECT DISTINCT USER_ID, 'Blood Pressure Systolic', 'mmHg' FROM PON.USER_BODYLOG_OLD WHERE BP_SYSTOLIC IS NOT NULL
    UNION ALL
    SELECT DISTINCT USER_ID, 'Blood Pressure Diastolic', 'mmHg' FROM PON.USER_BODYLOG_OLD WHERE BP_DIASTOLIC IS NOT NULL
    UNION ALL
    SELECT DISTINCT USER_ID, 'Heart Rate', 'bpm' FROM PON.USER_BODYLOG_OLD WHERE HEART_RATE_BPM IS NOT NULL
    UNION ALL
    SELECT DISTINCT USER_ID, 'Steps', 'steps' FROM PON.USER_BODYLOG_OLD WHERE STEPS_COUNT IS NOT NULL;

-- copy bodylog entries, preserving IDs so metric values below can reference them
INSERT INTO PON.USER_BODYLOG (ID, USER_ID, CREATED, USER_TIME)
    SELECT ID, USER_ID, CREATED, USER_TIME FROM PON.USER_BODYLOG_OLD;

-- keep the sequence in sync since we just inserted explicit IDs above
SELECT setval(pg_get_serial_sequence('PON.USER_BODYLOG', 'id'), COALESCE((SELECT MAX(ID) FROM PON.USER_BODYLOG), 1));

-- copy each legacy column's values into the new metric value table
INSERT INTO PON.USER_BODYLOG_METRIC (BODYLOG_ID, BODY_METRIC_ID, VALUE)
    SELECT o.ID, m.ID, o.WEIGHT_KG
    FROM PON.USER_BODYLOG_OLD o
    JOIN PON.USER_BODY_METRIC m ON m.USER_ID = o.USER_ID AND m.NAME = 'Weight'
    WHERE o.WEIGHT_KG IS NOT NULL;

INSERT INTO PON.USER_BODYLOG_METRIC (BODYLOG_ID, BODY_METRIC_ID, VALUE)
    SELECT o.ID, m.ID, o.HEIGHT_CM
    FROM PON.USER_BODYLOG_OLD o
    JOIN PON.USER_BODY_METRIC m ON m.USER_ID = o.USER_ID AND m.NAME = 'Height'
    WHERE o.HEIGHT_CM IS NOT NULL;

INSERT INTO PON.USER_BODYLOG_METRIC (BODYLOG_ID, BODY_METRIC_ID, VALUE)
    SELECT o.ID, m.ID, o.BODY_FAT_PERCENT
    FROM PON.USER_BODYLOG_OLD o
    JOIN PON.USER_BODY_METRIC m ON m.USER_ID = o.USER_ID AND m.NAME = 'Body Fat'
    WHERE o.BODY_FAT_PERCENT IS NOT NULL;

INSERT INTO PON.USER_BODYLOG_METRIC (BODYLOG_ID, BODY_METRIC_ID, VALUE)
    SELECT o.ID, m.ID, o.BMI
    FROM PON.USER_BODYLOG_OLD o
    JOIN PON.USER_BODY_METRIC m ON m.USER_ID = o.USER_ID AND m.NAME = 'BMI'
    WHERE o.BMI IS NOT NULL;

INSERT INTO PON.USER_BODYLOG_METRIC (BODYLOG_ID, BODY_METRIC_ID, VALUE)
    SELECT o.ID, m.ID, o.BP_SYSTOLIC
    FROM PON.USER_BODYLOG_OLD o
    JOIN PON.USER_BODY_METRIC m ON m.USER_ID = o.USER_ID AND m.NAME = 'Blood Pressure Systolic'
    WHERE o.BP_SYSTOLIC IS NOT NULL;

INSERT INTO PON.USER_BODYLOG_METRIC (BODYLOG_ID, BODY_METRIC_ID, VALUE)
    SELECT o.ID, m.ID, o.BP_DIASTOLIC
    FROM PON.USER_BODYLOG_OLD o
    JOIN PON.USER_BODY_METRIC m ON m.USER_ID = o.USER_ID AND m.NAME = 'Blood Pressure Diastolic'
    WHERE o.BP_DIASTOLIC IS NOT NULL;

INSERT INTO PON.USER_BODYLOG_METRIC (BODYLOG_ID, BODY_METRIC_ID, VALUE)
    SELECT o.ID, m.ID, o.HEART_RATE_BPM
    FROM PON.USER_BODYLOG_OLD o
    JOIN PON.USER_BODY_METRIC m ON m.USER_ID = o.USER_ID AND m.NAME = 'Heart Rate'
    WHERE o.HEART_RATE_BPM IS NOT NULL;

INSERT INTO PON.USER_BODYLOG_METRIC (BODYLOG_ID, BODY_METRIC_ID, VALUE)
    SELECT o.ID, m.ID, o.STEPS_COUNT
    FROM PON.USER_BODYLOG_OLD o
    JOIN PON.USER_BODY_METRIC m ON m.USER_ID = o.USER_ID AND m.NAME = 'Steps'
    WHERE o.STEPS_COUNT IS NOT NULL;

DROP TABLE PON.USER_BODYLOG_OLD;
