

CREATE TABLE IF NOT EXISTS PON.USER_ACTIVITY (
    ID                  SERIAL PRIMARY KEY,
    USER_ID             INTEGER NOT NULL REFERENCES PON.USER(ID),
    CREATED             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    NAME                VARCHAR(255) NOT NULL,
    TAG_ID              INTEGER NOT NULL REFERENCES PON.USER_TAG(ID),
    DURATION            INTEGER NOT NULL,
    NOTE                TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS PON.USER_REMINDER (
    ID                  SERIAL PRIMARY KEY,
    USER_ID             INTEGER NOT NULL REFERENCES PON.USER(ID),
    CREATED             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    ENABLED             BOOLEAN NOT NULL DEFAULT TRUE,
    INTERVAL_MINUTES    INTEGER NOT NULL,
    LAST_ACTIVITY_AT    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Minimal cron-like schedule string: "D:HHMM-HHMM" windows (day 0=Sun..6=Sat)
    -- joined by the ASCII Unit Separator (0x1F), same encoding as goalspage's tag
    -- based goals. Interpreted entirely client-side; empty string means the reminder
    -- never fires.
    CRON                TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS PON.USER_REMINDER_ACTIVITY (
    REMINDER_ID         INTEGER NOT NULL REFERENCES PON.USER_REMINDER(ID) ON DELETE CASCADE,
    ACTIVITY_ID         INTEGER NOT NULL REFERENCES PON.USER_ACTIVITY(ID) ON DELETE CASCADE
);
