ALTER TABLE PON.USER_REMINDER
ADD COLUMN ACTIVITY_MODE VARCHAR(64) NOT NULL DEFAULT 'random';

ALTER TABLE PON.USER_REMINDER
ADD COLUMN ACTIVE_TIMERS TEXT NOT NULL DEFAULT '{}';

ALTER TABLE PON.USER_REMINDER
ADD COLUMN SOUND VARCHAR(64) NOT NULL DEFAULT 'chime';

ALTER TABLE PON.USER_REMINDER
ADD COLUMN NAME VARCHAR(128) NOT NULL DEFAULT '';
