CREATE TABLE IF NOT EXISTS PON.USER_EXERCISE (
    ID                  SERIAL PRIMARY KEY,
    USER_ID             INTEGER NOT NULL REFERENCES PON.USER(ID),
    CREATED             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    NAME                VARCHAR(255) NOT NULL,
    NOTE                TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS PON.USER_EXERCISE_TAG (
    EXERCISE_ID         INTEGER NOT NULL REFERENCES PON.USER_EXERCISE(ID) ON DELETE CASCADE,
    TAG_ID              INTEGER NOT NULL REFERENCES PON.USER_TAG(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PON.USER_WORKOUT (
    ID                  SERIAL PRIMARY KEY,
    USER_ID             INTEGER NOT NULL REFERENCES PON.USER(ID),
    CREATED             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    NAME                VARCHAR(255) NOT NULL,
    NOTE                TEXT NOT NULL DEFAULT '',

    -- JSON blob holding the workout's sets and steps.
    STRUCTURE           TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS PON.USER_WORKOUT_TAG (
    WORKOUT_ID          INTEGER NOT NULL REFERENCES PON.USER_WORKOUT(ID) ON DELETE CASCADE,
    TAG_ID              INTEGER NOT NULL REFERENCES PON.USER_TAG(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PON.USER_WORKOUTLOG (
    ID                  SERIAL PRIMARY KEY,
    USER_ID             INTEGER NOT NULL REFERENCES PON.USER(ID),
    WORKOUT_ID          INTEGER REFERENCES PON.USER_WORKOUT(ID) ON DELETE SET NULL,
    CREATED             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    NAME                VARCHAR(255) NOT NULL,
    START_TIME          TIMESTAMP NOT NULL,
    STOP_TIME           TIMESTAMP NOT NULL,
    PAUSED_MS           BIGINT NOT NULL DEFAULT 0,
    COMPLETED           BOOLEAN NOT NULL DEFAULT FALSE,
    NOTE                TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS PON.USER_WORKOUTLOG_STEP (
    ID                  SERIAL PRIMARY KEY,
    USER_ID             INTEGER NOT NULL REFERENCES PON.USER(ID),
    WORKOUTLOG_ID       INTEGER NOT NULL REFERENCES PON.USER_WORKOUTLOG(ID) ON DELETE CASCADE,
    EXERCISE_ID         INTEGER REFERENCES PON.USER_EXERCISE(ID) ON DELETE SET NULL,

    NAME                VARCHAR(255) NOT NULL,
    KIND                VARCHAR(32) NOT NULL,
    -- Where the step was in the workout when it ran, all counting from 1.
    -- e.g. SET_NUMBER = 2, ROUND = 3, STEP = 1 is the first step of the third round of the second set.
    SET_NUMBER          INTEGER NOT NULL,
    ROUND               INTEGER NOT NULL,
    STEP                INTEGER NOT NULL,

    TARGET_SECONDS      INTEGER NOT NULL DEFAULT 0,
    TARGET_REPS         INTEGER NOT NULL DEFAULT 0,
    TARGET_WEIGHT       FLOAT NOT NULL DEFAULT 0,
    TARGET_DISTANCE     FLOAT NOT NULL DEFAULT 0,
    ACTUAL_REPS         INTEGER NOT NULL DEFAULT 0,
    -- Seconds spent on the step, not counting pauses. 0 means it was skipped.
    ACTUAL_SECONDS      INTEGER NOT NULL DEFAULT 0,
    ACTUAL_WEIGHT       FLOAT NOT NULL DEFAULT 0,
    ACTUAL_DISTANCE     FLOAT NOT NULL DEFAULT 0,
    UNIT                VARCHAR(32) NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS PON.USER_WORKOUTLOG_TIMESPAN (
    WORKOUTLOG_ID       INTEGER NOT NULL REFERENCES PON.USER_WORKOUTLOG(ID) ON DELETE CASCADE,
    TIMESPAN_ID         INTEGER NOT NULL REFERENCES PON.USER_TIMESPAN(ID) ON DELETE CASCADE
);
