ALTER TABLE PON.USER_TIMESPAN_TAG
DROP CONSTRAINT user_timespan_tag_tag_id_fkey;

ALTER TABLE PON.USER_TIMESPAN_TAG
ADD CONSTRAINT user_timespan_tag_tag_id_fkey FOREIGN KEY (TAG_ID) REFERENCES PON.USER_TAG(ID) ON DELETE CASCADE;
